### PR TITLE
Add AUTHENTICATE method

### PR DESCRIPTION
**Pull request by ikrivosheev**
Issue: https://github.com/bamthomas/aioimaplib/issues/2
I'll add the tests a little bit later

### CODE REVIEW

**Comment by WolkoDav** [comment]
@bamthomas, can you look and review this MR?

**Comment by bamthomas** [comment]
I'm currently not available, could this wait until next week ?

**Comment by WolkoDav** [comment]
Yes, not problem

**Comment by bamthomas** [comment]
Sorry for being this late. First thank you for your pull request. I have few questions : 

- why do we have to implement a base64 encode/decode ?
- why the API is different from IMAP4 python lib ? 
- would it be possible to name variables explicitly (i.e. try to avoid one or two letter(s) names when it is not obvious) ?

Until now I tried to stick to the API of IMAP4 because :
- it has been used for years
- if people want to migrate from the multithreaded to async it should be easy
- it is a way to validate in two steps (first the use of the real lib to build the mock server capability, then the same test with aioimaplib)

I haven't seen an authenticate test in  test_imapserver_imaplib.py.

**Comment by WolkoDav** [comment]
Thank you for the review, I will correct your comments

**Pull request closed without merging**
