### PR TITLE
Pytest, tox and GHA

### PR DESCRIPTION
**Pull request by azmeuk**
Hi.

This patch brings changes on the unit tests side:

-  It uses pytest instead of nosetests. Pytest is more and more popular these days, and the support for nose is starting to dwindle.
- It adds tox so the unit tests can be ran with several python versions.
- It uses GHA instead of TravisCI (the TravisCI project behind the README badge links to a 404).

If you are OK with this PR, I can submit another one where I move from the `nosetests` assertion style to the `pytest` one. This would avoid the current warnings:

```
aioimaplib/tests/test_imapserver.py::TestMailToString::test_message_not_quoted_printable
  /home/azmeuk/dev/aioimaplib/aioimaplib/tests/test_imapserver.py:68: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals('Bonjour à vous', m.get_payload(decode=True).decode())
```

There was a test failing, and I did not fix it to not mix everything up:

```python
    async def test_get_quotaroot(self):
        imap_client = await self.login_user('user', 'pass')
        self.imapserver.receive(Mail.create(['user']))

        response = await imap_client.getquotaroot('INBOX')

>       self.assertEqual(response.lines, [b'INBOX (STORAGE 292 5000)', b'GETQUOTAROOT completed.'])
E       AssertionError: Lists differ: [b'INBOX (STORAGE 294 5000)', b'GETQUOTAROOT completed.'] != [b'INBOX (STORAGE 292 5000)', b'GETQUOTAROOT completed.']
E
E       First differing element 0:
E       b'INBOX (STORAGE 294 5000)'
E       b'INBOX (STORAGE 292 5000)'
E
E       - [b'INBOX (STORAGE 294 5000)', b'GETQUOTAROOT completed.']
E       ?                     ^
E
E       + [b'INBOX (STORAGE 292 5000)', b'GETQUOTAROOT completed.']
E       ?                     ^

aioimaplib/tests/test_aioimaplib.py:734: AssertionError
```

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@azmeuk hello! Can you add skip run GA on change `**.rst`?

**Comment by azmeuk** [comment]
I am not sure to understand. Do you mean I should configure GHA so it is not triggered when a rst file is edited?

**Comment by ikrivosheev** [comment]
> I am not sure to understand. Do you mean I should configure GHA so it is not triggered when a rst file is edited?

Yes, exactly) sorry for my English...

**Comment by azmeuk** [comment]
Here it is :)

**Comment by bamthomas** [comment]
@azmeuk the build is failing and I don't have time for now to dig into it.
could you have a look ?

**Comment by azmeuk** [comment]
Yes, I will look at this is the coming days.

**Comment by azmeuk** [comment]
This is fixed with #86

**Pull request merged**
